# Generated by Django 4.2.2 on 2023-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='project',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='uploads/default_img.png', upload_to='uploads/'),
        ),
    ]
