# Generated by Django 4.2.2 on 2023-06-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_photo_project_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ManyToManyField(to='portfolio.photo'),
        ),
    ]
